### ISSUE TITLE
Alle datasett har fått tilknytting til API'er

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-etl#4]
Åpne et datasett og se på:
"Brukt i datatjeneste (API)"
Se for eksempel på datasettet:
https://data.norge.no/datasets/2058f4e4-7fce-4b3f-ad34-34dbf526297d

![image](https://user-images.githubusercontent.com/39513382/91842848-09434400-ec55-11ea-94b5-3eaa16d21628.png)

**Comment by NilsOveTen** [comment]
Request payload i nåværende portal er:
```
{dataseturi: "https://data.norge.no/node/1115"}
```
Det må endres til:
```
{
    "filters": [
        {
            "servesDataset.keyword": "https://data.norge.no/node/314"
        }
    ]
}
```

**Comment by lillelars** [comment]
Testet OK i prod.
